# Generated by Django 5.2.5 on 2025-08-31 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='available_count',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
